INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_SPECTROSCOPY spectroscopy)

FIND_PATH(
    SPECTROSCOPY_INCLUDE_DIRS
    NAMES spectroscopy/api.h
    HINTS $ENV{SPECTROSCOPY_DIR}/include
        ${PC_SPECTROSCOPY_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    SPECTROSCOPY_LIBRARIES
    NAMES gnuradio-spectroscopy
    HINTS $ENV{SPECTROSCOPY_DIR}/lib
        ${PC_SPECTROSCOPY_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPECTROSCOPY DEFAULT_MSG SPECTROSCOPY_LIBRARIES SPECTROSCOPY_INCLUDE_DIRS)
MARK_AS_ADVANCED(SPECTROSCOPY_LIBRARIES SPECTROSCOPY_INCLUDE_DIRS)

